[workspace]

members = ["omr_core"]

resolver = "2"

[workspace.dependencies]
tracing = "0.1"
thiserror = "2"
num-traits = "0.2"
rand_core = "0.6"
rand = "0.8"
rand_distr = "0.4"
itertools = "0.14"
rayon = "1.10"

algebra = { git = "https://github.com/primus-labs/primus-fhe", branch = "simplify_fhe_api" }
lattice = { git = "https://github.com/primus-labs/primus-fhe", branch = "simplify_fhe_api" }
fhe_core = { git = "https://github.com/primus-labs/primus-fhe", branch = "simplify_fhe_api" }

# algebra = { path = "../primus-fhe/algebra" }
# lattice = { path = "../primus-fhe/lattice" }
# fhe_core = { path = "../primus-fhe/fhe_core" }

criterion = "0.5"

[profile.bench]
lto = true
codegen-units = 1
